import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";

import postgres from "postgres";

const RUN_ID_PATTERN = /^[a-z0-9][a-z0-9-]{0,39}$/;
const GENERATED_RUN_MARKER = "PLAYWRIGHT_E2E_GENERATED_RUN_ID";

function fixtureUuid(source: string) {
  const hash = createHash("md5").update(source).digest("hex");
  const value = `${hash.slice(0, 12)}5${hash.slice(13, 16)}a${hash.slice(17)}`;
  return [
    value.slice(0, 8),
    value.slice(8, 12),
    value.slice(12, 16),
    value.slice(16, 20),
    value.slice(20),
  ].join("-");
}

export function configurePreviewFixtureEnvironment() {
  if (!process.env.SUPABASE_DB_URL?.trim()) {
    return;
  }

  const runId = process.env.E2E_RUN_ID?.trim();
  if (
    process.env[GENERATED_RUN_MARKER] !== "true" ||
    !runId ||
    !RUN_ID_PATTERN.test(runId)
  ) {
    throw new Error(
      "Playwright E2E run ID must be generated by e2e/run-playwright.mjs.",
    );
  }
  const prefix = `e2e-preview-${runId}`;

  process.env.E2E_ADVISOR_PROFILE_ID = fixtureUuid(`${prefix}:advisor-1`);
  process.env.E2E_SECOND_ADVISOR_PROFILE_ID = fixtureUuid(
    `${prefix}:advisor-2`,
  );
  process.env.E2E_STUDENT_PROFILE_ID = fixtureUuid(
    `${prefix}:organization-student`,
  );
  process.env.E2E_APPLICATION_STUDENT_PROFILE_ID = fixtureUuid(
    `${prefix}:application-student`,
  );
  process.env.E2E_APPLICATION_INTAKE_ID = fixtureUuid(`${prefix}:intake`);
}

async function executeFixtureScript(filename: string) {
  const databaseUrl = process.env.SUPABASE_DB_URL?.trim();
  const runId = process.env.E2E_RUN_ID?.trim();
  if (!databaseUrl || !runId) return;
  if (!RUN_ID_PATTERN.test(runId)) {
    throw new Error("Generated Preview E2E run ID is invalid.");
  }

  const source = await readFile(
    path.join(process.cwd(), "supabase/fixtures", filename),
    "utf8",
  );
  const sqlText = source
    .replaceAll("\\set ON_ERROR_STOP on", "")
    .replaceAll(":'run_id'", `'${runId}'`)
    .replaceAll(
      ":'admin_email'",
      `'${process.env.E2E_ADMIN_EMAIL?.trim().replaceAll("'", "''") ?? ""}'`,
    );
  const sql = postgres(databaseUrl, {
    max: 1,
    onnotice: () => undefined,
  });

  try {
    await sql.unsafe(sqlText);
  } finally {
    await sql.end();
  }
}

export async function provisionPreviewFixtures() {
  if (!process.env.SUPABASE_DB_URL?.trim()) {
    return;
  }

  try {
    await executeFixtureScript("preview_e2e.sql");
  } catch (error) {
    await executeFixtureScript("cleanup_preview_e2e.sql").catch(
      () => undefined,
    );
    throw error;
  }
}

export async function cleanupPreviewFixtures() {
  await executeFixtureScript("cleanup_preview_e2e.sql");
}
